replicaCount: 1

image:
  repository: registry.digitalocean.com/circleguard/circleguard-services
  pullPolicy: IfNotPresent
  tag: ""  # Overridden by pipeline: --set image.tag=<service>-sha-<commit>

service:
  type: ClusterIP
  port: 8085

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

startupProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8085
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 12

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8085
  initialDelaySeconds: 0
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8085
  initialDelaySeconds: 20
  periodSeconds: 5

env:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

envFrom:
  - secretRef:
      name: notification-service-secret
      # Keys expected: JWT_SECRET
