{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.services }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ . }}-external-secret
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ . }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $.Values.externalSecrets.smSecretPath }}
{{- end }}
{{- end }}
