{{- if .Values.jaeger.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
    circleguard/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.jaeger.image }}:{{ .Values.jaeger.tag }}"
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
          ports:
            - containerPort: 6831
              protocol: UDP
              name: compact
            - containerPort: 14268
              name: collector
            - containerPort: 9411
              name: zipkin
            - containerPort: 16686
              name: ui
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
    circleguard/component: observability
spec:
  selector:
    app: jaeger
  ports:
    - name: compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: collector
      port: 14268
      targetPort: 14268
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
{{- end }}
