# Bitnami PostgreSQL values
auth:
  database: circleguard
  username: circleguard
  existingSecret: postgresql-secret
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
