# Neo4j Helm values
neo4j:
  name: neo4j
  passwordFromSecret: neo4j-secret  # secret created by bootstrap-cluster.sh

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 5Gi

config:
  NEO4J_PLUGINS: '["apoc"]'
  NEO4J_dbms_connector_bolt_advertised__address: ":7687"
